// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: e-invoice-proxy-ctl/inter_comm_server_client_msg.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//命令字
type CMD int32

const (
	CMD_CMD_NONE              CMD = 0
	CMD_CMD_HEART_BEAT_REQ    CMD = 1  //心跳请求
	CMD_CMD_HEART_BEAT_RSP    CMD = 2  //心跳响应;body为空
	CMD_CMD_OPEN_URL_REQ      CMD = 3  //打开税局url
	CMD_CMD_OPEN_URL_RSP      CMD = 4  //打开税局url响应;body为空
	CMD_CMD_PROXY_REQ         CMD = 5  //代理请求
	CMD_CMD_PROXY_RSP         CMD = 6  //代理请求响应;body非空
	CMD_CMD_UPLOAD_LOGIN_REQ  CMD = 7  //上报税号登录态
	CMD_CMD_UPLOAD_LOGIN_RSP  CMD = 8  //上报税号登录态响应;body非空
	CMD_CMD_UPLOAD_COOKIE_REQ CMD = 9  //上传cookie
	CMD_CMD_UPLOAD_COOKIE_RSP CMD = 10 //上传cookie响应;body为空
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0:  "CMD_NONE",
		1:  "CMD_HEART_BEAT_REQ",
		2:  "CMD_HEART_BEAT_RSP",
		3:  "CMD_OPEN_URL_REQ",
		4:  "CMD_OPEN_URL_RSP",
		5:  "CMD_PROXY_REQ",
		6:  "CMD_PROXY_RSP",
		7:  "CMD_UPLOAD_LOGIN_REQ",
		8:  "CMD_UPLOAD_LOGIN_RSP",
		9:  "CMD_UPLOAD_COOKIE_REQ",
		10: "CMD_UPLOAD_COOKIE_RSP",
	}
	CMD_value = map[string]int32{
		"CMD_NONE":              0,
		"CMD_HEART_BEAT_REQ":    1,
		"CMD_HEART_BEAT_RSP":    2,
		"CMD_OPEN_URL_REQ":      3,
		"CMD_OPEN_URL_RSP":      4,
		"CMD_PROXY_REQ":         5,
		"CMD_PROXY_RSP":         6,
		"CMD_UPLOAD_LOGIN_REQ":  7,
		"CMD_UPLOAD_LOGIN_RSP":  8,
		"CMD_UPLOAD_COOKIE_REQ": 9,
		"CMD_UPLOAD_COOKIE_RSP": 10,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{0}
}

//rpa命令字
type RPACMD int32

const (
	RPACMD_RPA_NONE       RPACMD = 0 //执行js
	RPACMD_RPA_JS         RPACMD = 1 //执行js
	RPACMD_RPA_ID         RPACMD = 2 //查找id
	RPACMD_RPA_CLASS_NAME RPACMD = 3 //查找className
	RPACMD_RPA_TAG_NAME   RPACMD = 4 //查找tagName
)

// Enum value maps for RPACMD.
var (
	RPACMD_name = map[int32]string{
		0: "RPA_NONE",
		1: "RPA_JS",
		2: "RPA_ID",
		3: "RPA_CLASS_NAME",
		4: "RPA_TAG_NAME",
	}
	RPACMD_value = map[string]int32{
		"RPA_NONE":       0,
		"RPA_JS":         1,
		"RPA_ID":         2,
		"RPA_CLASS_NAME": 3,
		"RPA_TAG_NAME":   4,
	}
)

func (x RPACMD) Enum() *RPACMD {
	p := new(RPACMD)
	*p = x
	return p
}

func (x RPACMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPACMD) Descriptor() protoreflect.EnumDescriptor {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_enumTypes[1].Descriptor()
}

func (RPACMD) Type() protoreflect.EnumType {
	return &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_enumTypes[1]
}

func (x RPACMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPACMD.Descriptor instead.
func (RPACMD) EnumDescriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{1}
}

//前后端通信通用结构
type SendMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd         CMD    `protobuf:"varint,1,opt,name=cmd,proto3,enum=einvoiceproxyctl.CMD" json:"cmd,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` //SAAS平台登录成功的token,客户端请求服务器用
	LogId       string `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	RespCode    int32  `protobuf:"varint,4,opt,name=resp_code,json=respCode,proto3" json:"resp_code,omitempty"`
	RespMessage string `protobuf:"bytes,5,opt,name=resp_message,json=respMessage,proto3" json:"resp_message,omitempty"`
	Body        []byte `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SendMsg) Reset() {
	*x = SendMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsg) ProtoMessage() {}

func (x *SendMsg) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsg.ProtoReflect.Descriptor instead.
func (*SendMsg) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{0}
}

func (x *SendMsg) GetCmd() CMD {
	if x != nil {
		return x.Cmd
	}
	return CMD_CMD_NONE
}

func (x *SendMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendMsg) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *SendMsg) GetRespCode() int32 {
	if x != nil {
		return x.RespCode
	}
	return 0
}

func (x *SendMsg) GetRespMessage() string {
	if x != nil {
		return x.RespMessage
	}
	return ""
}

func (x *SendMsg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HeaderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 头部信息的键名
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 头部信息的键值
}

func (x *HeaderInfo) Reset() {
	*x = HeaderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderInfo) ProtoMessage() {}

func (x *HeaderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderInfo.ProtoReflect.Descriptor instead.
func (*HeaderInfo) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeaderInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

//代理请求
type ProxyRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req       string        `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`                              //请求流水号
	Url       string        `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                              //代理请求url
	HeadInfos []*HeaderInfo `protobuf:"bytes,3,rep,name=head_infos,json=headInfos,proto3" json:"head_infos,omitempty"` //请求局端信息头
	ReqData   []byte        `protobuf:"bytes,4,opt,name=req_data,json=reqData,proto3" json:"req_data,omitempty"`       //代理请求数据
}

func (x *ProxyRequestReq) Reset() {
	*x = ProxyRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequestReq) ProtoMessage() {}

func (x *ProxyRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequestReq.ProtoReflect.Descriptor instead.
func (*ProxyRequestReq) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyRequestReq) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

func (x *ProxyRequestReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProxyRequestReq) GetHeadInfos() []*HeaderInfo {
	if x != nil {
		return x.HeadInfos
	}
	return nil
}

func (x *ProxyRequestReq) GetReqData() []byte {
	if x != nil {
		return x.ReqData
	}
	return nil
}

//代理响应
type ProxyRequestRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     string `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`                        // 请求流水号
	RspData []byte `protobuf:"bytes,2,opt,name=rsp_data,json=rspData,proto3" json:"rsp_data,omitempty"` //代理请求响应数据
}

func (x *ProxyRequestRsp) Reset() {
	*x = ProxyRequestRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyRequestRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequestRsp) ProtoMessage() {}

func (x *ProxyRequestRsp) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequestRsp.ProtoReflect.Descriptor instead.
func (*ProxyRequestRsp) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyRequestRsp) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *ProxyRequestRsp) GetRspData() []byte {
	if x != nil {
		return x.RspData
	}
	return nil
}

// 上报税号登录态
type UploadLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessId       int32  `protobuf:"varint,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`                    //业务id
	OpenEnterpriseId string `protobuf:"bytes,2,opt,name=open_enterprise_id,json=openEnterpriseId,proto3" json:"open_enterprise_id,omitempty"` //社会信用代码，aes加密再base64传输
	LoginFlag        int32  `protobuf:"varint,3,opt,name=login_flag,json=loginFlag,proto3" json:"login_flag,omitempty"`                       //登录态；1:已登录；2:未登录
}

func (x *UploadLogin) Reset() {
	*x = UploadLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogin) ProtoMessage() {}

func (x *UploadLogin) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogin.ProtoReflect.Descriptor instead.
func (*UploadLogin) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{4}
}

func (x *UploadLogin) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *UploadLogin) GetOpenEnterpriseId() string {
	if x != nil {
		return x.OpenEnterpriseId
	}
	return ""
}

func (x *UploadLogin) GetLoginFlag() int32 {
	if x != nil {
		return x.LoginFlag
	}
	return 0
}

type UploadCookie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessId       int32      `protobuf:"varint,1,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`                    //业务id
	OpenEnterpriseId string     `protobuf:"bytes,2,opt,name=open_enterprise_id,json=openEnterpriseId,proto3" json:"open_enterprise_id,omitempty"` //社会信用代码，aes加密再base64传输
	Cookies          []*Cookies `protobuf:"bytes,3,rep,name=cookies,proto3" json:"cookies,omitempty"`                                             //cookie信息
	BrowserRequest   string     `protobuf:"bytes,4,opt,name=browser_request,json=browserRequest,proto3" json:"browser_request,omitempty"`         //用户登录成功后的请求头json字符串
}

func (x *UploadCookie) Reset() {
	*x = UploadCookie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCookie) ProtoMessage() {}

func (x *UploadCookie) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCookie.ProtoReflect.Descriptor instead.
func (*UploadCookie) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{5}
}

func (x *UploadCookie) GetBusinessId() int32 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *UploadCookie) GetOpenEnterpriseId() string {
	if x != nil {
		return x.OpenEnterpriseId
	}
	return ""
}

func (x *UploadCookie) GetCookies() []*Cookies {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *UploadCookie) GetBrowserRequest() string {
	if x != nil {
		return x.BrowserRequest
	}
	return ""
}

type Cookies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`        //Cookie的名称
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`    //Cookie的值
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`  //Cookie的所在域
	Expire int64  `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"` //Cookie的过期时间
}

func (x *Cookies) Reset() {
	*x = Cookies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cookies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cookies) ProtoMessage() {}

func (x *Cookies) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cookies.ProtoReflect.Descriptor instead.
func (*Cookies) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{6}
}

func (x *Cookies) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Cookies) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cookies) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cookies) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type RPAInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpaCmd  RPACMD `protobuf:"varint,1,opt,name=rpa_cmd,json=rpaCmd,proto3,enum=einvoiceproxyctl.RPACMD" json:"rpa_cmd,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` //需要执行的js语句或需查找的元素名称
}

func (x *RPAInfo) Reset() {
	*x = RPAInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPAInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPAInfo) ProtoMessage() {}

func (x *RPAInfo) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPAInfo.ProtoReflect.Descriptor instead.
func (*RPAInfo) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{7}
}

func (x *RPAInfo) GetRpaCmd() RPACMD {
	if x != nil {
		return x.RpaCmd
	}
	return RPACMD_RPA_NONE
}

func (x *RPAInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

//打开税局url
type OpenUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url                     string     `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	LoginSuccessFlagRpa     []*RPAInfo `protobuf:"bytes,2,rep,name=login_success_flag_rpa,json=loginSuccessFlagRpa,proto3" json:"login_success_flag_rpa,omitempty"`             //检查登录成功的页面元素标志，需按顺序传入
	CheckLoginSuccessRpa    []*RPAInfo `protobuf:"bytes,3,rep,name=check_login_success_rpa,json=checkLoginSuccessRpa,proto3" json:"check_login_success_rpa,omitempty"`          //查看是否需要验证的rpa操作，需按顺序传入
	VertiftyLoginSuccessRpa []*RPAInfo `protobuf:"bytes,4,rep,name=vertifty_login_success_rpa,json=vertiftyLoginSuccessRpa,proto3" json:"vertifty_login_success_rpa,omitempty"` //是否验证成功的rpa操作，需按顺序传入
}

func (x *OpenUrl) Reset() {
	*x = OpenUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenUrl) ProtoMessage() {}

func (x *OpenUrl) ProtoReflect() protoreflect.Message {
	mi := &file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenUrl.ProtoReflect.Descriptor instead.
func (*OpenUrl) Descriptor() ([]byte, []int) {
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP(), []int{8}
}

func (x *OpenUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OpenUrl) GetLoginSuccessFlagRpa() []*RPAInfo {
	if x != nil {
		return x.LoginSuccessFlagRpa
	}
	return nil
}

func (x *OpenUrl) GetCheckLoginSuccessRpa() []*RPAInfo {
	if x != nil {
		return x.CheckLoginSuccessRpa
	}
	return nil
}

func (x *OpenUrl) GetVertiftyLoginSuccessRpa() []*RPAInfo {
	if x != nil {
		return x.VertiftyLoginSuccessRpa
	}
	return nil
}

var File_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto protoreflect.FileDescriptor

var file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDesc = []byte{
	0x0a, 0x36, 0x65, 0x2d, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2d, 0x63, 0x74, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x63, 0x74, 0x6c, 0x22, 0xb3, 0x01, 0x0a, 0x07, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x27, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x73, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x73, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x34, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x3b,
	0x0a, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x73, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72,
	0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7b, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x6f, 0x70, 0x65, 0x6e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x66, 0x6c,
	0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x46,
	0x6c, 0x61, 0x67, 0x22, 0xbb, 0x01, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6f, 0x70, 0x65, 0x6e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x52,
	0x07, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x72, 0x6f, 0x77,
	0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x61, 0x0a, 0x07, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x22, 0x56, 0x0a, 0x07, 0x52, 0x50, 0x41, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x31, 0x0a, 0x07, 0x72, 0x70, 0x61, 0x5f, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x63, 0x74, 0x6c, 0x2e, 0x52, 0x50, 0x41, 0x43, 0x4d, 0x44, 0x52, 0x06, 0x72, 0x70, 0x61, 0x43,
	0x6d, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x95, 0x02, 0x0a,
	0x07, 0x4f, 0x70, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x4e, 0x0a, 0x16, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x66, 0x6c, 0x61, 0x67,
	0x5f, 0x72, 0x70, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x69, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x52, 0x50,
	0x41, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x13, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x70, 0x61, 0x12, 0x50, 0x0a, 0x17, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x5f, 0x72, 0x70, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x65, 0x69,
	0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x63, 0x74, 0x6c, 0x2e, 0x52,
	0x50, 0x41, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x14, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x70, 0x61, 0x12, 0x56, 0x0a, 0x1a,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x66, 0x74, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x70, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x63, 0x74, 0x6c, 0x2e, 0x52, 0x50, 0x41, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x17, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x70, 0x61, 0x2a, 0xff, 0x01, 0x0a, 0x03, 0x43, 0x4d, 0x44, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x4d, 0x44, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4d,
	0x44, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x52, 0x45, 0x51,
	0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4d, 0x44, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x5f,
	0x42, 0x45, 0x41, 0x54, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4d,
	0x44, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x55, 0x52, 0x4c, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03,
	0x12, 0x14, 0x0a, 0x10, 0x43, 0x4d, 0x44, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x55, 0x52, 0x4c,
	0x5f, 0x52, 0x53, 0x50, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4d, 0x44, 0x5f, 0x50, 0x52,
	0x4f, 0x58, 0x59, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4d, 0x44,
	0x5f, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14,
	0x43, 0x4d, 0x44, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e,
	0x5f, 0x52, 0x45, 0x51, 0x10, 0x07, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x50,
	0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x08,
	0x12, 0x19, 0x0a, 0x15, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x43,
	0x4f, 0x4f, 0x4b, 0x49, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x09, 0x12, 0x19, 0x0a, 0x15, 0x43,
	0x4d, 0x44, 0x5f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x43, 0x4f, 0x4f, 0x4b, 0x49, 0x45,
	0x5f, 0x52, 0x53, 0x50, 0x10, 0x0a, 0x2a, 0x54, 0x0a, 0x06, 0x52, 0x50, 0x41, 0x43, 0x4d, 0x44,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x50, 0x41, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x50, 0x41, 0x5f, 0x4a, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x50,
	0x41, 0x5f, 0x49, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x50, 0x41, 0x5f, 0x43, 0x4c,
	0x41, 0x53, 0x53, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x50,
	0x41, 0x5f, 0x54, 0x41, 0x47, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x04, 0x42, 0x14, 0x5a, 0x12,
	0x2e, 0x3b, 0x65, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x63,
	0x74, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescOnce sync.Once
	file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescData = file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDesc
)

func file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescGZIP() []byte {
	file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescOnce.Do(func() {
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescData)
	})
	return file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDescData
}

var file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_goTypes = []interface{}{
	(CMD)(0),                // 0: einvoiceproxyctl.CMD
	(RPACMD)(0),             // 1: einvoiceproxyctl.RPACMD
	(*SendMsg)(nil),         // 2: einvoiceproxyctl.SendMsg
	(*HeaderInfo)(nil),      // 3: einvoiceproxyctl.HeaderInfo
	(*ProxyRequestReq)(nil), // 4: einvoiceproxyctl.ProxyRequestReq
	(*ProxyRequestRsp)(nil), // 5: einvoiceproxyctl.ProxyRequestRsp
	(*UploadLogin)(nil),     // 6: einvoiceproxyctl.UploadLogin
	(*UploadCookie)(nil),    // 7: einvoiceproxyctl.UploadCookie
	(*Cookies)(nil),         // 8: einvoiceproxyctl.Cookies
	(*RPAInfo)(nil),         // 9: einvoiceproxyctl.RPAInfo
	(*OpenUrl)(nil),         // 10: einvoiceproxyctl.OpenUrl
}
var file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_depIdxs = []int32{
	0, // 0: einvoiceproxyctl.SendMsg.cmd:type_name -> einvoiceproxyctl.CMD
	3, // 1: einvoiceproxyctl.ProxyRequestReq.head_infos:type_name -> einvoiceproxyctl.HeaderInfo
	8, // 2: einvoiceproxyctl.UploadCookie.cookies:type_name -> einvoiceproxyctl.Cookies
	1, // 3: einvoiceproxyctl.RPAInfo.rpa_cmd:type_name -> einvoiceproxyctl.RPACMD
	9, // 4: einvoiceproxyctl.OpenUrl.login_success_flag_rpa:type_name -> einvoiceproxyctl.RPAInfo
	9, // 5: einvoiceproxyctl.OpenUrl.check_login_success_rpa:type_name -> einvoiceproxyctl.RPAInfo
	9, // 6: einvoiceproxyctl.OpenUrl.vertifty_login_success_rpa:type_name -> einvoiceproxyctl.RPAInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_init() }
func file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_init() {
	if File_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyRequestRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCookie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cookies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPAInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_goTypes,
		DependencyIndexes: file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_depIdxs,
		EnumInfos:         file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_enumTypes,
		MessageInfos:      file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_msgTypes,
	}.Build()
	File_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto = out.File
	file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_rawDesc = nil
	file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_goTypes = nil
	file_e_invoice_proxy_ctl_inter_comm_server_client_msg_proto_depIdxs = nil
}
